# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-04 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raise_invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raise_for', models.CharField(max_length=200)),
                ('email_to', models.EmailField(default='xyz@yahoo.com', max_length=254)),
                ('description_of_items', models.TextField(max_length=1000)),
                ('currency', models.CharField(max_length=10)),
                ('total_money', models.IntegerField(default=100)),
                ('paid', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(default='Hey! Attatched along is your Invoice', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='company_credentials',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
