# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-04 07:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoiceapp', '0002_auto_20160704_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='raise_invoice',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
