# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-26 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0002_auto_20160726_1123'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Raise_invoice',
            new_name='Invoice',
        ),
    ]
