# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-04 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0003_raise_invoice_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raise_invoice',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
