# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-03 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0004_invoice_raised_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='raised_by',
        ),
    ]
