# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-03 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0005_remove_invoice_raised_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='raised_by',
            field=models.CharField(default='', max_length=50),
        ),
    ]
