# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0006_auto_20160704_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raise_invoice',
            name='paid',
        ),
    ]
