# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-07 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0007_remove_raise_invoice_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='raise_invoice',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='raise_invoice',
            name='description_of_items',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='raise_invoice',
            name='message',
            field=models.TextField(default='Hey! Attatched along is your Invoice', max_length=500),
        ),
    ]
