# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-18 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0009_auto_20160707_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_credentials',
            name='website_url',
            field=models.URLField(max_length=100),
        ),
    ]
